Vagrant.configure("2") do |config|
      config.vm.box = "dummy"

      config.vm.provider :aws do |aws, override|
        aws.access_key_id = "AKIAIK63DNSWP544BAPQ"
        aws.secret_access_key = "9mSOy2Qhc7dOTYb8HFexe3Vo2+zvEHXpEAQZcfmT"
        aws.keypair_name = "Amazon"
        aws.region = "us-east-2"
        aws.ami = "ami-a7aa8ac2"
        aws.instance_type="t2.micro"
        override.ssh.username = "ubuntu"
        override.ssh.private_key_path = "./Amazon.pem"
      end
    end
